models:
  - name: stg_customers
    columns:
      - name: customerName
        tests:
          - string_not_empty:
              severity: error
          - unique:
              severity: error
          - not_null:
              severity: error

  - name: stg_orders
    columns:
      - name: status
        tests:
          - accepted_values:
              values: ['Shipped', 'Resolved', 'Cancelled','On Hold','Disputed','In Process']
              severity: error
